### ISSUE TITLE
The metadata association options based on external files MUST enable the user to specify the metadata format

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#150] opened 2016-04-14 13:40 UTC
This is quintessential for ingest in RODA and other systems.

Just add a combobox to next to the "choose directory" button. 
This is valid for the 3 of the 4 options in the second association page.

**Comment by adrapereira** [comment] 2016-04-14 14:04
Duplicate of #147

**Closed** 2016-04-26 17:11 UTC
Labels: duplicate, feature request
