### ISSUE TITLE
I have a question about RODA

### ISSUE THREAD

**Issue by anameegen** [keeps/roda-in#331] opened 2020-02-17 11:19 UTC
Greetings from Amsterdam!
I'm trying roda-in to maken SIPs in Bagit structure but I got an error:

![image](https://user-images.githubusercontent.com/8247074/74648766-95d95980-517e-11ea-82e5-99bbe3a8521e.png)
<img width="353" alt="error_rodain" src="https://user-images.githubusercontent.com/8247074/74648903-d0db8d00-517e-11ea-8985-029ec98ad4e2.PNG">

I still have many questions about the tool, I don't see features as:
- what is the basic structure that is need for the first import in roda-in? Roda-in ask to upload a folder: is it the objects only or also the checksums and bag-info.txt file?
- checksums: can roda-in be connected with total commander or give an error if I don't have a checksum manifest?
- can roda-in make the bag-it folder structure?  I couldn't see it - maybe because of the error - and the video's on Youtube shows eark  examples.
- classification schemes: there is an option for import or export. Are there examples or reusable objects for the schemes? What is the definition of "classification scheme" in the tool: is it the right statement? 
Kind regards,
Ana

**Comment by hsilva-keep** [comment] 2020-02-17 12:03
@anameegen I've moved your issue from RODA (Digital Preservation repository implementing main OAIS functional units) github repository to RODA-in (Desktop tool for creating Submission Information Packages/SIPs in different formats, e.g., E-ARK, BagIt) github repository as this seams a RODA-in related issue/set of questions.

To better understand the issue, can you please provide:
1. Operating system you are using
2. RODA-in version you are using
3. Describe the steps required to reproduce the issue (and if possible sample data/files)

I've just tested latest version (https://github.com/keeps/roda-in/releases/tag/2.2.0), both in Linux and Windows, and managed to generated a SIP in BagIt format.

Regarding you question, here are the answers:
> what is the basic structure that is need for the first import in roda-in? Roda-in ask to upload a folder: is it the objects only or also the checksums and bag-info.txt file?

When you execute RODA-in, the first step is to choose a folder or set of folders where the files you want to package are on the filesystem. In the end, usually you will end up with some ZIP files, the packages, that you can then upload to RODA for example to be ingest.

> checksums: can roda-in be connected with total commander or give an error if I don't have a checksum manifest?

RODA-in, during the ZIP/package creation and if the package type allows it, calculates checksums and inserts them in their proper place (e.g. in BagIt, file manifest-md5.txt). No external tool can/will be used for this functionality.

 > can roda-in make the bag-it folder structure? I couldn't see it - maybe because of the error - and the video's on Youtube shows eark examples.

RODA-in does precisely that (when working properly, of course)

> classification schemes: there is an option for import or export. Are there examples or reusable objects for the schemes? What is the definition of "classification scheme" in the tool: is it the right statement?

This is related to RODA repository. In RODA, after creating an hierarchically organized set of digital objects, you might download that same information in a RODA specific format that can be imported in RODA-in. After importing, you can organized the new digital objects in RODA-in, and that information will be inserted in the package. That way, when uploading and ingesting the packages in RODA, those objects will be placed properly in the hierarchy.

**Comment by luis100** [comment] 2021-05-26 08:19
Closing due to inactivity

**Closed by luis100** 2021-05-26 08:19 UTC
